wandb: ERROR Invalid value for property run_name: <wandb.sdk.wandb_run.Run object at 0x7f9adc7b5360>.
Traceback (most recent call last):
  File "/data/zhaobo/zhouyufan/PDPP-Optimize/main_distributed.py", line 510, in <module>
    main()
  File "/data/zhaobo/zhouyufan/PDPP-Optimize/main_distributed.py", line 63, in main
    main_worker(args.gpu, ngpus_per_node, args)
  File "/data/zhaobo/zhouyufan/PDPP-Optimize/main_distributed.py", line 236, in main_worker
    wandb.init(project="MTID", name=wandb.init(project="MTID", name=wandb_name+ "_resume", config=args), config=args)
  File "/home/zhaoboqi/miniconda3/envs/MTID/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1239, in init
    wandb._sentry.reraise(e)
  File "/home/zhaoboqi/miniconda3/envs/MTID/lib/python3.10/site-packages/wandb/analytics/sentry.py", line 155, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhaoboqi/miniconda3/envs/MTID/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1224, in init
    wi.setup(kwargs)
  File "/home/zhaoboqi/miniconda3/envs/MTID/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 311, in setup
    settings._apply_init(kwargs)
  File "/home/zhaoboqi/miniconda3/envs/MTID/lib/python3.10/site-packages/wandb/sdk/wandb_settings.py", line 1877, in _apply_init
    self.update(init_settings, source=Source.INIT)
  File "/home/zhaoboqi/miniconda3/envs/MTID/lib/python3.10/site-packages/wandb/sdk/wandb_settings.py", line 1510, in update
    self.__dict__[key].update(value, source)
  File "/home/zhaoboqi/miniconda3/envs/MTID/lib/python3.10/site-packages/wandb/sdk/wandb_settings.py", line 598, in update
    self._value = self._validate(self._preprocess(value))
  File "/home/zhaoboqi/miniconda3/envs/MTID/lib/python3.10/site-packages/wandb/sdk/wandb_settings.py", line 571, in _validate
    raise SettingsValidationError(
wandb.sdk.wandb_settings.SettingsValidationError: Invalid value for property run_name: <wandb.sdk.wandb_run.Run object at 0x7f9adc7b5360>.